# This configuration file allows you to specify how different ip addresses get throttled

## Unlimited means no throttling at all
#unlimited: 1.2.3.5
#
## Blocked means this ip address is completely blocked from accessing the site
#blocked: 1.2.3.6
#
#daily: 
#  # A maximum of 10,000 hits per day
#  10000: 1.2.3.4
#hourly: 
#  # A maximum of 100 hits per hour. This is the default setting.
#  100: default
#  # This is an example of how you specify more than one ip address with a maximum of 200 hits per hour
#  200: 
#  - 1.2.3.7
#  - 1.2.3.8

# By default throttle API requests to 1200 requests per day. That's an average of 50 / hour.
daily:
  1200: default